apiVersion: apps/v1
kind: Deployment
metadata:
  name: coffeeshop-app-deployment
  labels:
    app: coffeeshop-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coffeeshop-app
  template:
    metadata:
      labels:
        app: coffeeshop-app
    spec:
      containers:
      - name: coffeeshop-app
        image: ashishpradhan92/cnb:81
        ports:
        - containerPort: 8083
        imagePullPolicy: Always
