apiVersion: apps/v1
kind: Deployment
metadata:
  name: coffeeshop-deployment
spec:
  replicas: 1  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: coffeeshop
  template:
    metadata:
      labels:
        app: coffeeshop
    spec:
      containers:
        - name: coffeeshop
          image: ashishpradhan92/cnb:68
          imagePullPolicy: Always
          ports:
            - containerPort: 80  # Adjust the container port as needed
