apiVersion: apps/v1
kind: Deployment
metadata:
  name: coffeeshop
spec:
  selector:
    matchLabels:
      app: coffeeshop
  template:
    metadata:
      labels:
        app: coffeeshop
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: ashishpradhan92/cnb:72
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
