apiVersion: v1
kind: Service
metadata:
  name: coffeeshop-app-svc
spec:
  selector:
    app: coffeeshop-app
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
      nodePort: 30001
  type: NodePort
